parameters:
    vidlis_security.authentication_handler: Vidlis\UserBundle\Handler\AuthenticationHandler
    vidlis_security.logout_handler: Vidlis\UserBundle\Handler\LogoutHandler

services:
    authentication_handler:
        class:  %vidlis_security.authentication_handler%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    logout_handler:
        class:  %vidlis_security.logout_handler%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
