parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    memcache_active: true

twig:
    globals:
        crawlable: "/youtube/app_dev.php"
        domain_name: "http://xavierp.synology.me/youtube/app_dev.php"
